#!/usr/bin/env python3
"""Regenerates source/Runtimes/manifest.json and each runtime project's archives.props
from the latest (or given) astral-sh/python-build-standalone release.

Usage: update-manifest.py [tag]

Run by the refresh-runtimes workflow (and manually). Only metadata is written; archives
are downloaded at pack time by the runtime csproj, verified against the sha256 here.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = "astral-sh/python-build-standalone"
TRIPLES = [
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]
ARCHIVE_RE = re.compile(
    r"^cpython-(?P<version>\d+\.\d+\.\d+[a-z0-9]*)\+(?P<tag>\d+)-(?P<triple>.+?)-install_only\.tar\.gz$"
)

runtimes_dir = Path(__file__).resolve().parent.parent


def fetch(url: str) -> bytes:
    # curl instead of urllib: avoids missing-CA issues with framework Pythons and works in CI.
    command = ["curl", "-fsSL", "--retry", "3", "-H", "User-Agent: PythonEmbedded.Net"]
    token = os.environ.get("GITHUB_TOKEN")
    if token and "api.github.com" in url:
        command += ["-H", f"Authorization: Bearer {token}"]
    return subprocess.run(command + [url], check=True, capture_output=True).stdout


def latest_tag() -> str:
    data = json.loads(fetch(f"https://api.github.com/repos/{REPO}/releases/latest"))
    return data["tag_name"]


def main() -> None:
    tag = sys.argv[1] if len(sys.argv) > 1 else latest_tag()
    sums = fetch(f"https://github.com/{REPO}/releases/download/{tag}/SHA256SUMS").decode()

    def version_key(v: str) -> tuple:
        # Stable beats pre-release of the same patch; otherwise numeric order.
        match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)([a-z0-9]*)", v)
        major, minor, patch, suffix = match.groups()
        return (int(major), int(minor), int(patch), suffix == "", suffix)

    # minor ("3.13") -> {"version": full, "assets": {triple: {"file", "sha256"}}}
    pythons: dict[str, dict] = {}
    for line in sums.splitlines():
        try:
            sha256, filename = line.split()
        except ValueError:
            continue
        match = ARCHIVE_RE.match(filename)
        if not match or match.group("triple") not in TRIPLES:
            continue
        version = match.group("version")
        minor = ".".join(version.split(".")[:2])
        entry = pythons.setdefault(minor, {"version": version, "assets": {}})
        if entry["version"] != version:
            if version_key(version) > version_key(entry["version"]):
                pythons[minor] = entry = {"version": version, "assets": {}}
            else:
                continue
        entry["assets"][match.group("triple")] = {"file": filename, "sha256": sha256}

    complete = {m: e for m, e in sorted(pythons.items()) if len(e["assets"]) == len(TRIPLES)}
    manifest = {"tag": tag, "repository": REPO, "pythons": complete}
    (runtimes_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"manifest.json: tag {tag}, {len(complete)} pythons: {', '.join(complete)}")

    for minor, entry in complete.items():
        project = runtimes_dir / f"PythonEmbedded.Net.Runtime.Python{minor.replace('.', '')}"
        if not project.is_dir():
            print(f"  (no project for {minor}, skipping props)")
            continue
        # NuGet version: "3.13.14.20260718" for stable, "3.15.0-b4.20260718" for pre-releases.
        numeric, _, suffix = re.fullmatch(r"(\d+\.\d+\.\d+)(([a-z0-9]*))", entry["version"]).groups()
        package_version = f"{numeric}-{suffix}.{tag}" if suffix else f"{numeric}.{tag}"
        lines = [
            "<!-- Generated by source/Runtimes/tools/update-manifest.py — do not edit. -->",
            "<Project>",
            "  <PropertyGroup>",
            f"    <PyRuntimeVersion>{package_version}</PyRuntimeVersion>",
            f"    <PyPythonVersion>{entry['version']}</PyPythonVersion>",
            f"    <PyReleaseTag>{tag}</PyReleaseTag>",
            "  </PropertyGroup>",
            "  <ItemGroup>",
        ]
        for triple in TRIPLES:
            asset = entry["assets"][triple]
            url = f"https://github.com/{REPO}/releases/download/{tag}/{asset['file']}"
            lines.append(
                f'    <PyArchive Include="{asset["file"]}" Url="{url}" Sha256="{asset["sha256"]}" />'
            )
        lines += ["  </ItemGroup>", "</Project>", ""]
        (project / "archives.props").write_text("\n".join(lines))
        print(f"  {project.name}: {entry['version']}+{tag}")


if __name__ == "__main__":
    main()
